--1

SELECT AEROPUERTOS.NOMBRE,AEROPUERTOS.PAIS , DIRECTOR.NOMBRE
FROM AEROPUERTOS,DIRECTOR 
WHERE CODIGO = COD_AEROPUERTO
AND AEROPUERTOS.PAIS = 'SPAIN' 
AND (UPPER(DIRECTOR.NOMBRE) SIMILAR TO '(A|E|I|O|U)%' OR UPPER(DIRECTOR.NOMBRE) SIMILAR TO '%(A|E|I|O|U)')
AND UPPER(DIRECTOR.PAIS) = 'ESPAÑA'
;

--2

    select aviones.*
    from aviones, volar
    where aviones.codigo = volar.cod_avion
    group by (aviones.codigo, aviones.linea_aerea, aviones.modelo, aviones.capacidad)
    having count(volar.cod_avion)>=2
    ;

--3

SELECT NUM_VUELO, FECHA_VUELO
FROM VOLAR
WHERE to_char(FECHA_VUELO, 'YYYY') = '2011'  
AND NUM_VUELO IN (SELECT NUM_VUELO FROM TENER_ESCALA GROUP BY NUM_VUELO HAVING COUNT(NUM_VUELO) >=2)
;

--4

SELECT NUM_VUELO, FECHA_VUELO
FROM VOLAR
WHERE to_char(FECHA_VUELO, 'YYYY') = '2011'  
AND NUM_VUELO IN (SELECT NUM_VUELO FROM TENER_ESCALA GROUP BY NUM_VUELO HAVING COUNT(NUM_VUELO) >=2)
;

--5

SELECT AVIONES.CODIGO, AVIONES.MODELO ,COUNT(VOLAR.COD_AVION)
FROM AVIONES, VOLAR
WHERE aviones.codigo = volar.cod_avion 
AND to_char(VOLAR.FECHA_VUELO, 'YYYY') = '2014' 
GROUP BY (AVIONES.CODIGO, AVIONES.MODELO)
HAVING COUNT(VOLAR.COD_AVION)>10
;

--6

    SELECT NOMBRE 
    FROM DIRECTOR
    WHERE DNI_CONTR IS NOT NULL AND length(NOMBRE) =10

    EXCEPT

    SELECT NOMBRE 
    FROM DIRECTOR
    WHERE UPPER(PAIS) != 'ESPAÑA'

    UNION

    SELECT NOMBRE 
    FROM DIRECTOR
    WHERE COD_AEROPUERTO IN (SELECT CODIGO FROM AEROPUERTOS WHERE UPPER(PAIS) = 'SWEDEN')
    ;

--7

SELECT AVIONES.CODIGO, AVIONES.MODELO
FROM AVIONES, VOLAR
WHERE aviones.codigo = volar.cod_avion 
AND AVIONES.CAPACIDAD BETWEEN 200 AND 400
AND VOLAR.PLAZAS_OCUPADAS = AVIONES.CAPACIDAD
;

--8

SELECT UPPER(LINEA_AEREA), count(CODIGO)
FROM AVIONES
WHERE UPPER(LINEA_AEREA) LIKE '%AIRLINES%'
GROUP BY UPPER(LINEA_AEREA)
ORDER BY count(CODIGO)
;