--1

SELECT SUM(MIN_JUGAR) FROM JUGAR;

--2

SELECT SUM(MIN_JUGAR) FROM JUGAR GROUP BY NOMBRE_JUG;

--3

SELECT NOMBRE_JUG, SUM(MIN_JUGAR) FROM JUGAR GROUP BY NOMBRE_JUG;

--4

SELECT SUM(MIN_JUGAR) FROM JUGAR WHERE to_char(FECHA_PART, 'YYYY') = '2010' GROUP BY NOMBRE_JUG;

--5

SELECT NOMBRE_JUG, DORSAL FROM JUGAR, JUGADOR WHERE  NOMBRE_JUG = NOMBRE AND UPPER(EQUIPO_JUGADOR) = 'ESPAÑA' GROUP BY NOMBRE_JUG, DORSAL HAVING COUNT(NOMBRE_JUG)>=14;

--6

SELECT NOMBRE_JUG, DORSAL FROM JUGAR, JUGADOR WHERE NOMBRE_JUG = NOMBRE AND to_char(FECHA_PART, 'YYYY') = '2010' AND UPPER(EQUIPO_JUGADOR) = 'ESPAÑA' GROUP BY NOMBRE_JUG, DORSAL HAVING COUNT(NOMBRE_JUG)>=14;

--7

SELECT NOMBRE_JUG, DORSAL FROM JUGAR, JUGADOR WHERE NOMBRE_JUG = NOMBRE AND UPPER(EQUIPO_JUGADOR) = 'ESPAÑA' GROUP BY NOMBRE_JUG, DORSAL HAVING SUM(MIN_JUGAR)>1200;